// Shared content shapes used across the site.
// Keeping these in one place means every data file (src/data/*.ts) and
// every component that renders that data agrees on the same fields.

export interface Service {
  /** Unique, URL-safe id. Used for React keys and the detail page URL (/services/:id). */
  id: string;
  title: string;
  /** One or two sentences shown on the Services cards and the Home preview. */
  shortDescription: string;
  /** Longer copy shown on the service's own detail page (/services/:id). */
  detailedDescription: string;
  /** Name of an icon from src/components/icons/ServiceIcons.tsx (see ICON_MAP there). */
  icon: string;
}

export interface Industry {
  /** Unique, URL-safe id. */
  id: string;
  name: string;
  /** Optional one-sentence note shown on the Industries page. Leave '' to omit. */
  description: string;
  /** Name of an icon from src/components/icons/ServiceIcons.tsx (see ICON_MAP there). */
  icon: string;
}

export type KnowledgeResourceType = 'Article' | 'Webinar' | 'Presentation' | 'Guide';

export interface KnowledgeResource {
  id: string;
  title: string;
  type: KnowledgeResourceType;
  /** ISO date string, e.g. '2026-08-15'. Used for sorting and display formatting. */
  date: string;
  description: string;
  /**
   * Where "View" links to — an external URL (a PDF, YouTube recording, blog post,
   * etc.). Leave '' to show the card without a link, e.g. for a "coming soon" entry.
   */
  url: string;
}

export type UpdateCategory =
  | 'Announcement'
  | 'Tax Update'
  | 'GST Update'
  | 'Firm News'
  | 'Regulatory Update';

export interface UpdateItem {
  id: string;
  title: string;
  /** ISO date string, e.g. '2026-08-15'. Used for sorting and display formatting. */
  date: string;
  category: UpdateCategory;
  description: string;
  /**
   * Optional "Read More" destination. Can be an external URL (e.g. a government
   * circular / press release) or left empty to hide the "Read More" link.
   */
  readMoreUrl?: string;
}

export interface LiveNewsItem {
  /** Circular/notification title, taken verbatim from the source. */
  title: string;
  /** Link to the official document (usually a PDF) — always opens in a new tab. */
  link: string;
}

/**
 * Shape of src/data/liveNews.json — auto-generated by
 * scripts/fetch-live-news.mjs on a schedule (see .github/workflows/fetch-news.yml).
 * Do not hand-edit this file; your edits will be overwritten on the next run.
 *
 * Source: the "What's New" circulars list on cbic-gst.gov.in (the official GST
 * portal run by CBIC, Government of India). No per-item publish date is
 * available from the source, so `updatedAt` reflects when THIS SITE last
 * synced — not when a given circular was actually issued.
 */
export interface LiveNewsFeedData {
  /** ISO timestamp of the last successful fetch, or null before the first run. */
  updatedAt: string | null;
  /** Human-readable name of the source, for attribution. */
  source: string;
  /** Link to the source page, for attribution. */
  sourceUrl: string;
  items: LiveNewsItem[];
}

export interface JobOpening {
  id: string;
  position: string;
  location: string;
  experience: string;
  employmentType: string;
  description: string;
  /**
   * Where the "Apply" button sends the applicant. Since this site has no backend,
   * use a `mailto:` link or a Google Form URL. See src/data/siteConfig.ts.
   */
  applyUrl: string;
}
